export const FETCH_REDIRECT_DATA_LOADING = 'FETCH_REDIRECT_DATA_LOADING';
export const FETCH_REDIRECT_DATA_SUCCESS = 'FETCH_REDIRECT_DATA_SUCCESS';
export const FETCH_REDIRECT_DATA_FAILED = 'FETCH_REDIRECT_DATA_FAILED';
export const FETCH_ALL_REDIRECT_DATA_SUCCESS = 'FETCH_ALL_REDIRECT_DATA_SUCCESS';